# -*- coding: utf-8 -*-
"""Optimization_Proyect_Bisection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CaYEr-PhpvuAiXl1_45qGXFXT6wIBoO8
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Callable, Optional


# 1. MODELO MATEMÁTICO (Definición de Funciones)


def f_recurso(h: np.ndarray) -> np.ndarray:
    """
    Calcula la función de distribución del recurso hídrico en el espacio.
    (Sustituye esta ecuación por la fórmula exacta de tu práctica)
    """
    return -0.1 * (h - 25)**2 + 100  # Ejemplo ilustrativo de un perfil convexo

def derivada_recurso(h: np.ndarray) -> np.ndarray:
    """
    Derivada analítica de la función del recurso.
    Los extremos locales del sistema se encuentran donde esta función se anula.
    """
    return -0.2 * (h - 25)


# 2. IMPLEMENTACIÓN DEL ALGORITMO NUMÉRICO (Módulo Genérico)

def metodo_biseccion(
    f: Callable[[float], float],
    a: float,
    b: float,
    tol: float = 1e-6,
    max_iter: int = 100
) -> Optional[float]:
    """
    Encuentra la raíz de una función continua en el intervalo [a, b]
    utilizando el método de bisección.

    Parámetros:
    -----------
    f        : Función continua a la que se le busca la raíz (ej. la derivada).
    a, b     : Extremos del intervalo de búsqueda inicial.
    tol      : Tolerancia absoluta para el criterio de parada (error máximo admitido).
    max_iter : Número máximo de iteraciones permitidas para evitar bucles infinitos.

    Devuelve:
    ---------
    float    : Aproximación numérica de la raíz.
    None     : Si el intervalo inicial no es válido (f(a) y f(b) tienen el mismo signo).
    """
    # Verificación del teorema de Bolzano
    if f(a) * f(b) > 0:
        print("[ERROR]: El intervalo inicial no cumple el Teorema de Bolzano f(a)*f(b) < 0.")
        return None

    print(f"{'Iteración':<10}{'Aproximación (c)':<20}{'Error admisible':<20}")
    print("-" * 50)

    for idx in range(1, max_iter + 1):
        # Punto medio del intervalo (reducción del espacio de búsqueda a la mitad)
        c = a + (b - a) / 2.0
        val_f = f(c)

        print(f"{idx:<10}{c:<20.12f}{abs(b - a):<20.2e}")

        # Criterios de parada: raíz exacta o tolerancia alcanzada
        if abs(val_f) <= 1e-15 or (b - a) / 2.0 < tol:
            print(f"\n[ÉXITO]: Algoritmo convergió en la iteración {idx}.")
            return c

        # Estrechamiento del intervalo según el signo
        if f(a) * val_f < 0:
            b = c
        else:
            a = c

    print("\n[ADVERTENCIA]: Se alcanzó el número máximo de iteraciones sin convergencia absoluta.")
    return c


# 3. EJECUCIÓN DE LA SIMULACIÓN

# Configuración de parámetros experimentales
LIM_INFERIOR = 0.0
LIM_SUPERIOR = 40.0
TOLERANCIA = 0.1
MAX_ITERACIONES = 100

# Llamada al motor numérico
h_optimo = metodo_biseccion(
    f=derivada_recurso,
    a=LIM_INFERIOR,
    b=LIM_SUPERIOR,
    tol=TOLERANCIA,
    max_iter=MAX_ITERACIONES
)

if h_optimo is not None:
    rendimiento_maximo = f_recurso(h_optimo)
    print(f"Punto crítico optimizado (h): {h_optimo:.4f}")
    print(f"Rendimiento máximo del recurso: {rendimiento_maximo:.4f}")